# Generated by Django 4.1.7 on 2023-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['student', 'course'], name='student_course_index'),
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['student'], name='student_index'),
        ),
    ]
