# Generated by Django 4.1.7 on 2023-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentcourse_student_course_index_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentcourse',
            new_name='studentcourse_both_index',
            old_name='student_course_index',
        ),
        migrations.RenameIndex(
            model_name='studentcourse',
            new_name='studentcourse_student_index',
            old_name='student_index',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher'], name='course_teacher_index'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['id'], name='course_id_index'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['id'], name='student_id_index'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['id'], name='teacher_id_index'),
        ),
    ]
