# Generated by Django 4.1.7 on 2023-04-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_course_name_index_student_student_name_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['fee'], name='course_fee_index'),
        ),
    ]
