# Generated by Django 4.1.7 on 2023-04-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='final_lab_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
