# Generated by Django 4.1.7 on 2023-03-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cnp', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=64)),
                ('county', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('mail_address', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
