# Generated by Django 4.1.7 on 2023-03-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_studentcourse_final_exam_scrore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='final_exam_scrore',
            new_name='final_exam_score',
        ),
    ]
